CREATE TABLE IF NOT EXISTS orders
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    active                   VARCHAR(255)   NOT NULL,
    version                  BIGINT         NOT NULL,
    created_at               TIMESTAMP WITHOUT TIME ZONE,
    updated_at               TIMESTAMP WITHOUT TIME ZONE,
    order_number             VARCHAR(40)    NOT NULL,
    user_id                  BIGINT         NOT NULL,
    status                   VARCHAR(30)    NOT NULL,
    total_amount             NUMERIC(19, 2) NOT NULL,
    currency                 VARCHAR(3)     NOT NULL,
    shipping_address         VARCHAR(500)   NOT NULL,
    payment_reference        VARCHAR(100),
    shipment_tracking_number VARCHAR(100),
    customer_email           VARCHAR(150)   NOT NULL,
    CONSTRAINT pk_orders PRIMARY KEY (id),
    CONSTRAINT uc_orders_order_number UNIQUE (order_number),
    CONSTRAINT fk_orders_user FOREIGN KEY (user_id) REFERENCES users (id)
    );

CREATE INDEX idx_orders_user_id ON orders (user_id);
CREATE INDEX idx_orders_status ON orders (status);
CREATE INDEX idx_orders_payment_reference ON orders (payment_reference);
CREATE INDEX idx_orders_tracking_number ON orders (shipment_tracking_number);


CREATE TABLE IF NOT EXISTS order_items
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    active       VARCHAR(255)   NOT NULL,
    version      BIGINT         NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    order_id     BIGINT         NOT NULL,
    product_name VARCHAR(200)   NOT NULL,
    product_sku  VARCHAR(80),
    quantity     INTEGER        NOT NULL,
    unit_price   NUMERIC(19, 2) NOT NULL,
    subtotal     NUMERIC(19, 2) NOT NULL,
    CONSTRAINT pk_order_items PRIMARY KEY (id),
    CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE
    );

CREATE INDEX idx_order_items_order_id ON order_items (order_id);


CREATE TABLE IF NOT EXISTS order_status_history
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    active      VARCHAR(255) NOT NULL,
    version     BIGINT       NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    order_id    BIGINT       NOT NULL,
    from_status VARCHAR(30),
    to_status   VARCHAR(30)  NOT NULL,
    source      VARCHAR(30)  NOT NULL,
    note        VARCHAR(500),
    CONSTRAINT pk_order_status_history PRIMARY KEY (id),
    CONSTRAINT fk_order_status_history_order FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE
    );

CREATE INDEX idx_order_status_history_order_id ON order_status_history (order_id);
