CREATE TABLE IF NOT EXISTS webhook_logs
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    active             VARCHAR(255) NOT NULL,
    version            BIGINT       NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    source             VARCHAR(30)  NOT NULL,
    event_type         VARCHAR(80),
    external_reference VARCHAR(150),
    payload            TEXT         NOT NULL,
    status             VARCHAR(30)  NOT NULL,
    error_message      VARCHAR(1000),
    processed_at       TIMESTAMP WITHOUT TIME ZONE,
    order_id           BIGINT,
    CONSTRAINT pk_webhook_logs PRIMARY KEY (id),
    CONSTRAINT fk_webhook_logs_order FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE SET NULL
    );

CREATE INDEX idx_webhook_logs_source ON webhook_logs (source);
CREATE INDEX idx_webhook_logs_status ON webhook_logs (status);
CREATE INDEX idx_webhook_logs_created_at ON webhook_logs (created_at);
CREATE INDEX idx_webhook_logs_external_ref ON webhook_logs (external_reference);
